images:
  vsphereCloudControllerManager: "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.21.0"
  csiAttacher: "quay.io/k8scsi/csi-attacher:v3.1.0"
  csiDriver: "gcr.io/cloud-provider-vsphere/csi/release/driver:v2.2.1"
  livenessProbe: "quay.io/k8scsi/livenessprobe:v2.2.0"
  vsphereSyncer: "gcr.io/cloud-provider-vsphere/csi/release/syncer:v2.2.1"
  csiProvisioner: "quay.io/k8scsi/csi-provisioner:v2.1.1"
  csiResizer: "quay.io/k8scsi/csi-resizer:v1.1.0"
  nodeDriverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v2.1.0"

vcenter:
  host: vcenter.local
  insecurehost: true
  username: usernmame@domain
  password: password
  datacenter: DatacenterName

kubelet:
  path: /var/lib/kubelet

storageclass:
  name: vsphere-csi
  default: true
  fstype: ext4
  storagepolicyname: Kubernetes
